# Generated by Django 6.0.1 on 2026-04-23 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dish_owner_order_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='qr_url',
        ),
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='secure_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(),
        ),
    ]
