# Generated by Django 4.2 on 2023-04-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_name',
            field=models.TextField(),
        ),
    ]
