# Generated by Django 4.2 on 2023-04-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_menu_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=255)),
            ],
        ),
    ]
