# Generated by Django 4.2 on 2023-04-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_selecteditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecteditems',
            name='reviews',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
