# Generated by Django 4.2 on 2023-05-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_selecteditems_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casestudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_pista', models.CharField(max_length=50)),
            ],
        ),
    ]
