# Generated by Django 4.2.1 on 2023-05-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_casestudy_review_pista'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='sarcasm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
